#!/usr/bin/env python3
"""Validate the twelve tracked registries against their Draft-07 JSON Schemas."""

import argparse
import csv
import json
import sys
from pathlib import Path
from urllib.parse import unquote

try:
    from jsonschema import Draft7Validator
    from jsonschema.exceptions import SchemaError
    from referencing import Registry
    from referencing.exceptions import Unresolvable
except ImportError:  # pragma: no cover - exercised only before dependency installation
    Draft7Validator = None
    Registry = None
    SchemaError = Exception
    Unresolvable = Exception

# ADR-002: "what ships" has one derived answer, site_build/shipped_pages.json, and
# consumers read it instead of re-deriving the shipped set from the producers.
sys.path.insert(0, str(Path(__file__).resolve().parent / "site_build"))

from shipped_pages import (  # noqa: E402
    RELATIVE_PATH as SHIPPED_PAGES_RELATIVE,
    ShippedPagesError,
    load_shipped_pages,
)


PAIRS = (
    ("topic_meta.json", "topic_meta.schema.json"),
    ("question_bank.json", "question_bank.schema.json"),
    ("communication_cases.json", "communication_cases.schema.json"),
    ("family_systems_scenarios.json", "family_systems_scenarios.schema.json"),
    ("evidence_registry.json", "evidence_registry.schema.json"),
    ("tool_registry.json", "tool_registry.schema.json"),
    ("curriculum.json", "curriculum.schema.json"),
    ("evidence_annotations.json", "evidence_annotations.schema.json"),
    ("instrument_rights.json", "instrument_rights.schema.json"),
    ("decisions.json", "decisions.schema.json"),
    ("pairings.json", "pairings.schema.json"),
    # Not at the repo root: it lives beside the producers it is derived from. Generated by
    # site_build/shipped_pages.py and gated by --check; registered here so a hand-edit or a
    # shape change is caught by the same validator every other registry answers to.
    (
        "13_Faculty_Resources/_automation/site_build/shipped_pages.json",
        "13_Faculty_Resources/_automation/site_build/shipped_pages.schema.json",
    ),
)


# Canonical id prefix per blueprint category. The schema pattern ^qb_[a-z]+_[0-9]{3}$
# cannot express this pairing, so it is enforced semantically here. Ids are permanent
# identities (SRS cards QB#<id> and cw_qb_v1 responses key on them), so the four
# pre-convention legacy ids are grandfathered rather than renamed.
QBANK_CANONICAL_PREFIXES = {
    "mood": "mood",
    "psychosis": "psy",
    "anxiety": "anx",
    "substance": "sud",
    "neurocog": "cog",
    "pharm": "pha",
    "safety": "saf",
    "personality": "per",
    "childdev": "cdev",
    "otherdx": "otherdx",
    "ethics": "eth",
    "relational": "rel",
}
QBANK_GRANDFATHERED_IDS = frozenset(
    {"qb_chd_001", "qb_chd_002", "qb_oth_001", "qb_oth_002"}
)


def qbank_prefix_diagnostics(document):
    """Semantic gate: each item id must use its category's canonical prefix."""
    diagnostics = []
    items = document.get("items", []) if isinstance(document, dict) else []
    for index, item in enumerate(items):
        if not isinstance(item, dict):
            continue
        item_id = item.get("id")
        category = item.get("category")
        if not isinstance(item_id, str) or category not in QBANK_CANONICAL_PREFIXES:
            continue  # shape problems are the schema's job
        if item_id in QBANK_GRANDFATHERED_IDS:
            continue
        expected = "qb_%s_" % QBANK_CANONICAL_PREFIXES[category]
        if not item_id.startswith(expected):
            diagnostics.append(
                "question_bank.json: INVALID at /items/%d/id: %r does not use the "
                "canonical prefix %r for category %r (grandfathered: %s)"
                % (
                    index,
                    item_id,
                    expected,
                    category,
                    ", ".join(sorted(QBANK_GRANDFATHERED_IDS)),
                )
            )
    return diagnostics


# Resolve page/tool references against the derived shipped listing, not against the
# shared manifest lists alone. Those lists are only one of four routes onto a site, so a
# pairing naming a Case-of-the-Week page or a resident-only tool used to read as dangling
# even though the build publishes it. shipped_pages.json is itself one of the PAIRS above:
# when it is missing or malformed, THAT pair reports it and this gate degrades to a single
# "cannot resolve references" line rather than crashing the whole validator.
PAIRINGS_SHIPPED_PAGES = Path(SHIPPED_PAGES_RELATIVE)
PAIRINGS_AUDIO_MANIFEST = Path("12_Media/audio_oe/MANIFEST.csv")
PAIRINGS_WEEKS = range(1, 7)
PAIRINGS_AUDIENCES = ("ms3", "res")


def pairings_integrity_diagnostics(document, root: Path):
    """Semantic gate: every pairing reference resolves, and every week/audience is covered.

    JSON Schema can check the SHAPE of a reference but not whether the page, tool or audio
    brief it names still exists. A dangling reference must fail the build, not the learner —
    a pairing is injected into all six week pages on both sites, so one renamed slug would
    ship a dead link six times over. Cross-item uniqueness of ``id`` is also beyond a
    per-item schema and is checked here.

    Page and tool refs resolve against shipped_pages.json, the one derived answer to what
    ships (ADR-002), so every route onto a site counts — the shared manifest lists, the
    Case-of-the-Week registry, and the resident-only and MS3-only extras alike.
    """
    diagnostics = []
    pairings = document.get("pairings", []) if isinstance(document, dict) else []

    pages, tools = set(), set()
    try:
        shipped = load_shipped_pages(root)
    except ShippedPagesError as error:
        diagnostics.append("pairings.json: cannot resolve references — %s" % error)
    else:
        pages = {p["slug"] for p in shipped["pages"] if p.get("kind") == "page"}
        tools = {p["slug"] for p in shipped["pages"] if p.get("kind") == "tool"}

    briefs = set()
    audio_path = root / PAIRINGS_AUDIO_MANIFEST
    try:
        with audio_path.open(encoding="utf-8") as handle:
            for row in csv.DictReader(handle):
                number = (row.get("number") or "").strip()
                if number:
                    briefs.add(number.lstrip("0") or "0")
    except OSError as error:
        diagnostics.append("pairings.json: cannot read %s: %s" % (PAIRINGS_AUDIO_MANIFEST, error))

    seen_ids = {}
    covered = set()
    for index, pairing in enumerate(pairings):
        if not isinstance(pairing, dict):
            continue  # shape problems are the schema's job
        pairing_id = pairing.get("id")
        if isinstance(pairing_id, str):
            if pairing_id in seen_ids:
                diagnostics.append(
                    "pairings.json: INVALID at /pairings/%d/id: %r duplicates /pairings/%d"
                    % (index, pairing_id, seen_ids[pairing_id])
                )
            else:
                seen_ids[pairing_id] = index
        for week in pairing.get("weeks", []) or []:
            for audience in pairing.get("audiences", []) or []:
                covered.add((week, audience))
        for item_index, item in enumerate(pairing.get("items", []) or []):
            if not isinstance(item, dict):
                continue
            kind, ref = item.get("kind"), item.get("ref")
            pointer = "/pairings/%d/items/%d/ref" % (index, item_index)
            if kind == "page" and pages and ref not in pages:
                diagnostics.append(
                    "pairings.json: INVALID at %s: page %r is not in %s"
                    % (pointer, ref, PAIRINGS_SHIPPED_PAGES.name)
                )
            elif kind == "tool" and tools and ref not in tools:
                diagnostics.append(
                    "pairings.json: INVALID at %s: tool %r is not in %s"
                    % (pointer, ref, PAIRINGS_SHIPPED_PAGES.name)
                )
            elif kind == "audio_oe" and briefs:
                key = str(ref).strip().lstrip("0") or "0"
                if key not in briefs:
                    diagnostics.append(
                        "pairings.json: INVALID at %s: audio_oe brief %r is not in %s"
                        % (pointer, ref, PAIRINGS_AUDIO_MANIFEST.name)
                    )

    for week in PAIRINGS_WEEKS:
        for audience in PAIRINGS_AUDIENCES:
            if (week, audience) not in covered:
                diagnostics.append(
                    "pairings.json: INVALID at /pairings: no pairing covers week %d for "
                    "audience %r — week%d.md would render an empty block"
                    % (week, audience, week)
                )
    return diagnostics


def json_pointer(path) -> str:
    """Format an iterable path as an RFC 6901-style JSON Pointer."""
    parts = (str(part).replace("~", "~0").replace("/", "~1") for part in path)
    return "/" + "/".join(parts)


def load_json(path: Path):
    try:
        with path.open(encoding="utf-8") as handle:
            return json.load(handle), None
    except FileNotFoundError:
        return None, f"{path.name}: MISSING"
    except json.JSONDecodeError as error:
        return None, f"{path.name}: INVALID JSON at line {error.lineno}, column {error.colno}: {error.msg}"
    except UnicodeDecodeError as error:
        return None, f"{path.name}: INVALID JSON at byte {error.start}: invalid UTF-8"
    except OSError as error:
        return None, f"{path.name}: UNREADABLE: {error}"


def local_fragment_target(schema, reference: str):
    """Return a local JSON Pointer target or raise ValueError if it is absent."""
    if not reference.startswith("#"):
        raise ValueError("non-local")

    pointer = unquote(reference[1:])
    if not pointer:
        return schema
    if not pointer.startswith("/"):
        raise ValueError("not a JSON Pointer")

    target = schema
    for token in pointer[1:].split("/"):
        decoded = []
        index = 0
        while index < len(token):
            if token[index] != "~":
                decoded.append(token[index])
                index += 1
                continue
            if index + 1 == len(token) or token[index + 1] not in "01":
                raise ValueError("invalid escape")
            decoded.append("~" if token[index + 1] == "0" else "/")
            index += 2
        token = "".join(decoded)
        if isinstance(target, dict):
            try:
                target = target[token]
            except KeyError as error:
                raise ValueError("missing target") from error
        elif isinstance(target, list) and token.isdigit() and str(int(token)) == token:
            index = int(token)
            if index >= len(target):
                raise ValueError("missing target")
            target = target[index]
        else:
            raise ValueError("missing target")
    return target


def schema_reference_error(schema):
    """Return the first deterministic invalid-reference location and reason."""
    def walk(node, path=()):
        if isinstance(node, dict):
            if path and "$id" in node:
                return (
                    json_pointer((*path, "$id")),
                    "nested resource scopes are unsupported",
                )
            if "$ref" in node:
                pointer = json_pointer((*path, "$ref"))
                reference = node["$ref"]
                if not isinstance(reference, str) or not reference.startswith("#"):
                    return pointer, "non-local $ref is not permitted"
                try:
                    target = local_fragment_target(schema, reference)
                except ValueError:
                    return pointer, "unresolved local $ref"
                try:
                    Draft7Validator.check_schema(target)
                except SchemaError:
                    return pointer, "local $ref target is not a valid Draft-07 schema"
            for key, value in node.items():
                error = walk(value, (*path, key))
                if error:
                    return error
        elif isinstance(node, list):
            for index, value in enumerate(node):
                error = walk(value, (*path, index))
                if error:
                    return error
        return None

    return walk(schema)


def validate_root(root: Path) -> tuple[list[str], bool]:
    """Return deterministic diagnostics for the twelve fixed registry/schema pairs."""
    diagnostics = []
    has_errors = False
    for document_name, schema_name in PAIRS:
        schema, schema_error = load_json(root / schema_name)
        if schema_error:
            diagnostics.append(schema_error)
            has_errors = True
            continue

        try:
            Draft7Validator.check_schema(schema)
        except SchemaError as error:
            diagnostics.append(
                f"{schema_name}: INVALID SCHEMA at {json_pointer(error.absolute_path)}: {error.message}"
            )
            has_errors = True
            continue

        reference_error = schema_reference_error(schema)
        if reference_error:
            pointer, reason = reference_error
            diagnostics.append(f"{schema_name}: INVALID SCHEMA at {pointer}: {reason}")
            has_errors = True
            continue

        document, document_error = load_json(root / document_name)
        if document_error:
            diagnostics.append(document_error)
            has_errors = True
            continue

        try:
            errors = sorted(
                Draft7Validator(schema, registry=Registry()).iter_errors(document),
                key=lambda error: (
                    json_pointer(error.absolute_path),
                    error.message,
                    json_pointer(error.absolute_schema_path),
                ),
            )
        except Unresolvable:
            diagnostics.append(f"{schema_name}: INVALID SCHEMA at /: unresolvable local $ref")
            has_errors = True
            continue
        if document_name == "question_bank.json":
            semantic = qbank_prefix_diagnostics(document)
        elif document_name == "pairings.json":
            semantic = pairings_integrity_diagnostics(document, root)
        else:
            semantic = []
        if errors or semantic:
            has_errors = True
            diagnostics.extend(
                f"{document_name}: INVALID at {json_pointer(error.absolute_path)}: {error.message}"
                for error in errors
            )
            diagnostics.extend(semantic)
        else:
            diagnostics.append(f"{document_name}: OK ({schema_name})")
    return diagnostics, has_errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="repository root containing the twelve fixed registry/schema pairs",
    )
    args = parser.parse_args()

    if Draft7Validator is None:
        print("jsonschema is required; install dependencies with: python3 -m pip install -r requirements.txt")
        return 2

    diagnostics, has_errors = validate_root(args.root)
    for diagnostic in diagnostics:
        print(diagnostic)
    return 1 if has_errors else 0


if __name__ == "__main__":
    sys.exit(main())
