import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const canonicalPath = path.join(dir, 'sp-interview.html');
const packPath = path.join(dir, 'sp-interview.pack.json');
const previewPath = path.join(dir, 'sp-interview.preview.html');
const marker = '<script>\n(function(){';
const previewConfig = {
  generated: true,
  providerMode: 'mock',
  endpoint: '',
  autoOpenSettings: false,
};

function buildPreview() {
  const canonical = fs.readFileSync(canonicalPath, 'utf8');
  const markerCount = canonical.split(marker).length - 1;
  if (markerCount !== 1) {
    throw new Error(`application script marker must occur exactly once; found ${markerCount}`);
  }

  const pack = JSON.parse(fs.readFileSync(packPath, 'utf8'));
  const injected = [
    '<!-- GENERATED by generate-preview.mjs; do not edit directly. -->',
    `<script>window.__SP_PREVIEW__=${JSON.stringify(previewConfig)};` +
      `window.__SP_PACK__=${JSON.stringify(pack)};</script>`,
  ].join('\n');

  return canonical.replace(marker, `${injected}\n${marker}`);
}

function main() {
  const mode = process.argv[2];
  if (process.argv.length !== 3 || !['--write', '--check'].includes(mode)) {
    console.error('Usage: node generate-preview.mjs --write|--check');
    process.exitCode = 2;
    return;
  }

  const expected = buildPreview();
  if (mode === '--write') {
    fs.writeFileSync(previewPath, expected, 'utf8');
    console.log('WROTE — sp-interview.preview.html');
    return;
  }

  let current = null;
  try {
    current = fs.readFileSync(previewPath, 'utf8');
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }
  if (current !== expected) {
    console.error('FAIL — sp-interview.preview.html is stale; run generate-preview.mjs --write');
    process.exitCode = 1;
    return;
  }
  console.log('PASS — sp-interview.preview.html is reproducible');
}

try {
  main();
} catch (error) {
  console.error(`FAIL — ${error.message}`);
  process.exitCode = 1;
}
