#!/usr/bin/env python3
"""Derive shipped_pages.json -- the one answer to "what ships".

WHY THIS EXISTS (ADR-002, beside this file)

    "What ships" had four producers and more than fifteen direct readers. Several
    readers privately re-derived the Case-of-the-Week slug from cotw_registry.json;
    the faculty console did not, and 22 pending case pages were invisible to
    attestation from 2026-07-09 to 2026-09-04 with nothing red anywhere (#517).

    A comment telling the next reader to remember the second source is a vigilance
    control, and vigilance is what failed. This file replaces it with a structural
    one: ONE tracked, generated listing, VERIFIED AGAINST THE REAL BUILD OUTPUT on
    every build. The derivation cannot drift from what the builds publish without
    build_and_check.sh going red, and the tracked file cannot go stale without
    --check going red in CI, in bin/verify.sh, and in the post-edit hook.

WHAT IT IS NOT: it does not decide what ships. The producers still do. This is a
listing derived FROM them, gated against them, and read INSTEAD of them.

USAGE
    python3 .../shipped_pages.py --write                    regenerate the tracked file
    python3 .../shipped_pages.py --check                    fail if the tracked file is stale
    python3 .../shipped_pages.py --check-build OUT --site ms3|res
                                                            fail if it disagrees with a build

DECISION: shipped-pages-single-source
"""

from __future__ import annotations

import argparse
import difflib
import glob
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import site_extras  # noqa: E402
from cotw_slug import COTW_DIR, COTW_REGISTRY, cotw_slug, cotw_weeks  # noqa: E402

ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
RELATIVE_PATH = "13_Faculty_Resources/_automation/site_build/shipped_pages.json"
MANIFEST_RELATIVE = "13_Faculty_Resources/_automation/site_build/site_manifest.json"
EXTRAS_RELATIVE = "13_Faculty_Resources/_automation/site_build/site_extras.py"

VERSION = 1
SITES = ("ms3", "res")
BOTH_SITES = ["ms3", "res"]
LEVEL_TITLES = {"ms3": "MS3", "res": "Resident"}

SCRIPT_RELATIVE = "13_Faculty_Resources/_automation/site_build/shipped_pages.py"

WRITE_COMMAND = "python3 %s --write" % SCRIPT_RELATIVE

NOTE = (
    "GENERATED by site_build/shipped_pages.py -- do not hand-edit. "
    "Regenerate: " + WRITE_COMMAND
)

# The files the derivation reads. Hashed into `generated_from` so a reader can
# explain a staleness failure; the GATE is regenerate-and-diff, never the hashes.
INPUT_FILES = (MANIFEST_RELATIVE, COTW_REGISTRY, EXTRAS_RELATIVE)


class ShippedPagesError(Exception):
    """The producers could not be read, or disagree with themselves."""


def _load_json(path, label):
    try:
        with open(path, encoding="utf-8") as handle:
            return json.load(handle)
    except (OSError, ValueError) as error:
        raise ShippedPagesError("%s: unreadable (%s)" % (label, error)) from error


def _sha256(path):
    try:
        with open(path, "rb") as handle:
            return hashlib.sha256(handle.read()).hexdigest()
    except OSError:
        return None


def _page(slug, kind, sites, title, source, producer):
    return {
        "slug": slug,
        "kind": kind,
        "sites": sorted(sites),
        "title": title,
        "source": source,
        "producer": producer,
    }


def _manifest_entries(manifest, key):
    entries = manifest.get(key, []) if isinstance(manifest, dict) else None
    if not isinstance(entries, list):
        raise ShippedPagesError("site_manifest.json: %s must be a list" % key)
    for entry in entries:
        if (
            not isinstance(entry, list)
            or len(entry) < 3
            or not all(isinstance(value, str) for value in entry[:3])
        ):
            raise ShippedPagesError("site_manifest.json: a %s entry is malformed" % key)
        yield entry[0], entry[1], entry[2]


def derive(root=ROOT):
    """The pure derivation: producers in, the shipped_pages document out.

    Same inputs always give byte-identical output -- pages sorted by slug, keys
    sorted, no timestamps, no build state.
    """
    root = os.path.abspath(os.fspath(root))
    manifest = _load_json(os.path.join(root, MANIFEST_RELATIVE), "site_manifest.json")

    by_slug = {}

    def add(page):
        existing = by_slug.get(page["slug"])
        if existing is not None:
            raise ShippedPagesError(
                "two producers claim the slug %r (%s and %s)"
                % (page["slug"], existing["producer"], page["producer"])
            )
        by_slug[page["slug"]] = page

    # 1 -- site_manifest.json: the shared pages and tools, on BOTH sites. The
    # resident build starts as a copytree of the MS3 build, so every shared page
    # reaches both deploys.
    for source, slug, title in _manifest_entries(manifest, "md"):
        add(_page(slug, "page", BOTH_SITES, title, source, "site_manifest"))
    for source, slug, title in _manifest_entries(manifest, "tools"):
        add(_page(slug, "tool", BOTH_SITES, title, source, "site_manifest"))

    # 2 -- MS3-only extras copied by build_deploy.py from _prototypes/. The
    # resident build removes them again, so they are ms3 only.
    for source, slug, title in site_extras.MS3_EXTRA_TOOLS:
        add(_page(slug, "tool", ["ms3"], title, source, "ms3_extra_tool"))

    # 3 -- cotw_registry.json: one MS3 page and one resident page per week,
    # appended to each build's own md list without touching the manifest.
    for week in cotw_weeks(root):
        if not isinstance(week, dict):
            raise ShippedPagesError("cotw_registry.json: a week is not an object")
        label = str(week.get("label") or "").strip()
        if not label:
            raise ShippedPagesError("cotw_registry.json: a week is missing its label")
        for level, source_key in (("ms3", "ms3_src"), ("res", "res_src")):
            source = week.get(source_key)
            if not isinstance(source, str) or not source:
                raise ShippedPagesError(
                    "cotw_registry.json: week %r is missing %s" % (label, source_key)
                )
            add(
                _page(
                    cotw_slug(week, level),
                    "page",
                    [level],
                    "%s — %s" % (label, LEVEL_TITLES[level]),
                    os.path.join(COTW_DIR, source),
                    "cotw_registry",
                )
            )

    # 4 -- resident-only markdown. Two entries deliberately reuse a slug the
    # manifest already ships (welcome.md, cotw_index.md): the resident build
    # OVERWRITES the inherited page rather than adding one, so those are not new
    # shipped pages and must not appear twice.
    for source, slug, title in site_extras.RESIDENT_EXTRA_PAGES:
        if slug in by_slug:
            continue  # resident override of a page that already ships on both sites
        add(_page(slug, "page", ["res"], title, source, "resident_extra"))

    # 5 -- resident-only prototype tools. These DO ship: _build/res/tools/.
    for source, slug, title in site_extras.RESIDENT_PROTO_TOOLS:
        add(_page(slug, "tool", ["res"], title, source, "resident_tool"))

    generated_from = {}
    for relative in INPUT_FILES:
        digest = _sha256(os.path.join(root, relative))
        if digest is not None:
            generated_from[os.path.basename(relative)] = digest

    return {
        "version": VERSION,
        "_note": NOTE,
        "generated_from": generated_from,
        "pages": sorted(by_slug.values(), key=lambda page: page["slug"]),
    }


def serialize(document):
    """The exact bytes of the tracked file. 2-space indent, sorted keys, LF."""
    return json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def load_shipped_pages(root=ROOT):
    """Read the tracked artifact. THE function every new consumer should call.

    Returns the parsed document. Raises ShippedPagesError when it is unreadable
    or is not the shape this module writes -- a silently short universe is the
    failure ADR-002 exists to end, so there is no permissive fallback.
    """
    document = _load_json(
        os.path.join(os.fspath(root), RELATIVE_PATH), "shipped_pages.json"
    )
    if not isinstance(document, dict) or document.get("version") != VERSION:
        raise ShippedPagesError("shipped_pages.json: unexpected version")
    pages = document.get("pages")
    if not isinstance(pages, list) or not pages:
        raise ShippedPagesError("shipped_pages.json: pages must be a non-empty list")
    for page in pages:
        if (
            not isinstance(page, dict)
            or not isinstance(page.get("slug"), str)
            or not page["slug"]
        ):
            raise ShippedPagesError("shipped_pages.json: a page entry is malformed")
        sites = page.get("sites")
        if (
            not isinstance(sites, list)
            or not sites
            or any(site not in SITES for site in sites)
        ):
            raise ShippedPagesError(
                "shipped_pages.json: %s has malformed sites" % page.get("slug")
            )
    return document


def slugs_for_site(document, site):
    """Every slug the named site publishes, as a set."""
    return {page["slug"] for page in document["pages"] if site in page["sites"]}


# ---------------------------------------------------------------------------
# modes
# ---------------------------------------------------------------------------


def _breakdown(document):
    counts = {}
    for page in document["pages"]:
        counts[page["producer"]] = counts.get(page["producer"], 0) + 1
    return ", ".join("%d %s" % (count, name) for name, count in sorted(counts.items()))


def write(root=ROOT):
    document = derive(root)
    path = os.path.join(root, RELATIVE_PATH)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(serialize(document))
    print(
        "shipped_pages.json written — %d page(s): %s"
        % (len(document["pages"]), _breakdown(document))
    )
    return 0


def check(root=ROOT):
    """Regenerate in memory and diff against the tracked file."""
    expected = serialize(derive(root))
    path = os.path.join(root, RELATIVE_PATH)
    try:
        with open(path, encoding="utf-8") as handle:
            actual = handle.read()
    except OSError as error:
        print("shipped_pages.json STALE — cannot read the tracked file: %s" % error)
        print("Regenerate it:  %s" % WRITE_COMMAND)
        return 1
    if actual == expected:
        document = json.loads(actual)
        print(
            "shipped_pages OK — %d page(s) derived from the producers: %s"
            % (len(document["pages"]), _breakdown(document))
        )
        return 0
    print("shipped_pages.json STALE — a producer changed and the tracked file did not.")
    print("Regenerate it:  %s" % WRITE_COMMAND)
    print()
    for line in difflib.unified_diff(
        actual.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile="shipped_pages.json (tracked)",
        tofile="shipped_pages.json (derived)",
    ):
        sys.stdout.write(line)
    return 1


def built_slugs(out_dir):
    """What a finished build actually publishes: content/*.md + tools/*.html.

    Everything else under tools/ (packs, vendored JS, media) is an asset that
    rides along with a tool, not a page anyone attests.
    """
    out_dir = os.fspath(out_dir).rstrip("/\\")
    found = {
        os.path.basename(p) for p in glob.glob(os.path.join(out_dir, "content", "*.md"))
    }
    found |= {
        os.path.basename(p) for p in glob.glob(os.path.join(out_dir, "tools", "*.html"))
    }
    return found


def check_build(out_dir, site, root=ROOT):
    """THE structural guarantee: the tracked listing equals the real build.

    A disagreement in either direction fails the build. That is what makes this
    a derivation from reality rather than a second thing to remember.
    """
    if site not in SITES:
        print("unknown site %r (expected ms3|res)" % site)
        return 2
    if not os.path.isdir(out_dir):
        print("shipped_pages --check-build: %s is not a build directory" % out_dir)
        return 2
    try:
        document = load_shipped_pages(root)
    except ShippedPagesError as error:
        print("shipped_pages --check-build INVALID — %s" % error)
        return 1

    expected = slugs_for_site(document, site)
    actual = built_slugs(out_dir)
    only_tracked = sorted(expected - actual)
    only_built = sorted(actual - expected)
    if not only_tracked and not only_built:
        print(
            "shipped_pages --check-build OK — %s publishes exactly the %d tracked slug(s)"
            % (site, len(expected))
        )
        return 0

    print(
        "shipped_pages --check-build FAILED — %s: %d tracked slug(s) not built, "
        "%d built slug(s) not tracked." % (site, len(only_tracked), len(only_built))
    )
    for slug in only_tracked:
        print(
            "  - %s: shipped_pages.json says %s ships it; the build did not produce it"
            % (slug, site)
        )
    for slug in only_built:
        print(
            "  + %s: the %s build published it and shipped_pages.json does not list it. "
            "A page that ships must be attestable — wire its producer into "
            "site_build/shipped_pages.py, then run: %s" % (slug, site, WRITE_COMMAND)
        )
    return 1


def main(argv=None):
    parser = argparse.ArgumentParser(description="Derive and gate shipped_pages.json.")
    parser.add_argument("--root", default=ROOT, help="repository root")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="regenerate the tracked file")
    group.add_argument("--check", action="store_true", help="fail if the tracked file is stale")
    group.add_argument(
        "--check-build",
        metavar="OUT",
        help="fail if the tracked file disagrees with a finished build directory",
    )
    parser.add_argument("--site", choices=SITES, help="which site --check-build is verifying")
    args = parser.parse_args(argv)

    root = os.path.abspath(args.root)
    try:
        if args.write:
            return write(root)
        if args.check:
            return check(root)
        if not args.site:
            parser.error("--check-build requires --site ms3|res")
        return check_build(args.check_build, args.site, root)
    except ShippedPagesError as error:
        print("shipped_pages INVALID — %s" % error)
        return 1


if __name__ == "__main__":
    sys.exit(main())
