/* Closed rotation-edition catalog boundary.  Deliberately has no browser I/O. */
var FD_EDITION_CATALOG=(function(){
  'use strict';
  function fdEditionCatalogMarker(){}
  var own=Object.prototype.hasOwnProperty;
  var branded=new WeakSet(), privateIndex=new WeakMap();
  var KEY=/^[a-z0-9][a-z0-9._:-]{0,126}@v[1-9][0-9]{0,5}$/;
  var DIGEST=/^sha256-[A-Za-z0-9_-]{43}$/;
  var CORE=/^[0-9a-f]{40}$/;
  var DATE=/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/;
  var TIME=/^(?:[01][0-9]|2[0-3]):[0-5][0-9]$/;
  var MAX=4096, MAX_DEPTH=48;
  var TEMPLATE_TOKENS={
    arrival:['timing','time','place','role'],scheduleWindow:['dayStart','dayEnd','endQualifier'],
    scheduleRangeWithPlace:['daySet','startTime','endTime','activity','place','priority'],scheduleRangeWithoutPlace:['daySet','startTime','endTime','activity','priority'],
    schedulePointWithPlace:['daySet','startTime','activity','place','priority'],schedulePointWithoutPlace:['daySet','startTime','activity','priority'],
    rounds:['preparation','participation','followUp'],presentation:['format','timing','elements'],documentation:['workflow','timing'],
    attendance:['events','absenceRole'],feedback:['cadence','initiator','setting'],access:['item','due'],contact:['role'],checklist:['item','priority'],
    resourceWithReason:['title','priority','week','reason','hostname'],resourceWithoutReason:['title','priority','week','hostname'],changeSummary:['kinds','count']
  };
  var AUTHORITY={coreLabel:'Reviewed clerkship Library',localLabel:'Local rotation guidance',requiredLabel:'Required by this local rotation',recommendedLabel:'Recommended by this local rotation',optionalLabel:'Optional for this local rotation',resourceLabel:'Locally curated official resource',localBoundary:'Local rotation guidance does not replace current institutional policy or supervision.',documentationGuardrail:'Use only the approved institutional record. Do not place patient information in this site. Complete documentation only with supervisor guidance and review.'};
  function failure(code,path){ return {code:code||'CATALOG_INVALID',path:path||'/',message:'The reviewed rotation catalog is unavailable.',blocking:true}; }
  function frozen(value){ var keys,i; if(value&&typeof value==='object'&&!Object.isFrozen(value)){ keys=Object.keys(value); for(i=0;i<keys.length;i++) frozen(value[keys[i]]); Object.freeze(value); } return value; }
  function plainCopy(value,seen,depth){
    var proto,keys,out,i,key,d,ld,length;
    if(value===null||typeof value==='string'||typeof value==='boolean') return value;
    if(typeof value==='number'){ if(!isFinite(value)||Math.floor(value)!==value) throw Error('invalid'); return value; }
    if(!value||typeof value!=='object'||depth>MAX_DEPTH) throw Error('invalid');
    if(seen.indexOf(value)>=0) throw Error('cycle'); seen.push(value);
    try{ proto=Object.getPrototypeOf(value); }catch(ignoreProto){ throw Error('proxy'); }
    if(proto!==Object.prototype&&proto!==null&&!(Array.isArray(value)&&proto===Array.prototype)) throw Error('prototype');
    if(Array.isArray(value)){
      try{ ld=Object.getOwnPropertyDescriptor(value,'length'); }catch(ignoreLength){ throw Error('proxy'); }
      if(!ld||!own.call(ld,'value')||typeof ld.value!=='number'||ld.value<0||ld.value>MAX||Math.floor(ld.value)!==ld.value) throw Error('array');
      length=ld.value; keys=Reflect.ownKeys(value); if(keys.length!==length+1) throw Error('sparse'); out=[];
      for(i=0;i<length;i++){ key=String(i); try{ d=Object.getOwnPropertyDescriptor(value,key); }catch(ignoreDescriptor){ throw Error('proxy'); } if(!d||!d.enumerable||!own.call(d,'value')) throw Error('array'); out.push(plainCopy(d.value,seen,depth+1)); }
    }else{
      try{ keys=Reflect.ownKeys(value); }catch(ignoreKeys){ throw Error('proxy'); } out=Object.create(null);
      for(i=0;i<keys.length;i++){ key=keys[i]; if(typeof key!=='string') throw Error('symbol'); try{ d=Object.getOwnPropertyDescriptor(value,key); }catch(ignoreObjectDescriptor){ throw Error('proxy'); }
        if(!d||!d.enumerable||!own.call(d,'value')||key==='__proto__'||key==='constructor'||key==='prototype') throw Error('property'); out[key]=plainCopy(d.value,seen,depth+1); }
    }
    seen.pop(); return out;
  }
  function copy(value){ return plainCopy(value,[],0); }
  function canonical(value){ var keys,i,out=[]; if(value===null||typeof value==='string'||typeof value==='boolean'||typeof value==='number') return JSON.stringify(value); if(Array.isArray(value)){ for(i=0;i<value.length;i++) out.push(canonical(value[i])); return '['+out.join(',')+']'; } keys=Object.keys(value).sort(); for(i=0;i<keys.length;i++) out.push(JSON.stringify(keys[i])+':'+canonical(value[keys[i]])); return '{'+out.join(',')+'}'; }
  function bytes(value){ return new TextEncoder().encode(canonical(value)); }
  function base64url(buffer){ var bytes=new Uint8Array(buffer),binary='',i; for(i=0;i<bytes.length;i++) binary+=String.fromCharCode(bytes[i]); return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''); }
  function digest(value,subtle){ if(!subtle||typeof subtle.digest!=='function') return Promise.reject(Error('digest')); try{return Promise.resolve(subtle.digest('SHA-256',bytes(value))).then(function(result){ if(!result||typeof result.byteLength!=='number'||result.byteLength!==32) throw Error('digest'); return 'sha256-'+base64url(result); });}catch(ignore){return Promise.reject(Error('digest'));} }
  function exact(value,fields){ var keys=Object.keys(value).sort(), wanted=fields.slice().sort(); return keys.length===wanted.length&&keys.every(function(key,index){return key===wanted[index];}); }
  function text(value){ return typeof value==='string'&&value.length>0&&!/[\x00-\x1f\x7f-\x9f\u202a-\u202e\u2066-\u2069<>&]/.test(value)&&value===value.trim(); }
  function setOf(values,allowed){ return Array.isArray(values)&&values.length>0&&values.length<=MAX&&values.every(function(v,i){return typeof v==='string'&&allowed(v)&&(i===0||values[i-1]<v);}); }
  function recordShape(record){
    var kind=record.kind, fields={trainingLocation:['key','kind','contentDigest','displayName','locationCode','locationTypeCode','audiences','officialHostnames','verifiedOn'],curatorProfile:['key','kind','contentDigest','displayName','roleKey','locationKeys','audiences','verifiedOn'],place:['key','kind','contentDigest','displayName','locationKeys','audiences','verifiedOn'],officialLink:['key','kind','contentDigest','title','url','visibleHostname','purposeCode','locationKeys','audiences','verifiedOn'],phraseSet:['key','kind','contentDigest','displayName','templates','audiences','verifiedOn'],choice:['key','kind','contentDigest','choiceKind','label','fragment','audiences','verifiedOn'],localPreset:['key','kind','contentDigest','displayName','localPlan','locationKeys','phraseSetKey','audiences','verifiedOn']}[kind];
    if(!fields||!(exact(record,fields)||((kind==='choice'||kind==='phraseSet')&&exact(record,fields.concat(['locationKeys']))))||!KEY.test(record.key)||!DIGEST.test(record.contentDigest)||!setOf(record.audiences,function(v){return v==='ms3'||v==='resident';})||!DATE.test(record.verifiedOn)) return false;
    if(kind==='trainingLocation') return text(record.displayName)&&/^[A-Z0-9]{2,8}$/.test(record.locationCode)&&['inpatient','outpatient','consult-liaison','emergency','community','mixed'].indexOf(record.locationTypeCode)>=0&&Array.isArray(record.officialHostnames)&&record.officialHostnames.every(function(v){return /^[a-z0-9](?:[a-z0-9.-]{0,251}[a-z0-9])?$/.test(v);});
    if(kind==='choice') return text(record.label)&&text(record.fragment)&&['reason','activity','role','checklist','daySet','roundsPreparation','roundsParticipation','roundsFollowUp','presentationFormat','presentationTiming','presentationElement','documentationWorkflow','documentationTiming','feedbackCadence','feedbackInitiator','feedbackSetting','accessItem','duePoint'].indexOf(record.choiceKind)>=0&&(!own.call(record,'locationKeys')||scope(record));
    if(kind==='officialLink') return text(record.title)&&/^https:\/\//.test(record.url)&&text(record.visibleHostname)&&scope(record);
    if(kind==='phraseSet') return text(record.displayName)&&templateShape(record.templates)&&(!own.call(record,'locationKeys')||scope(record));
    return text(record.displayName)&&scope(record);
  }
  function scope(record){ return Array.isArray(record.locationKeys)&&setOf(record.locationKeys,function(v){return KEY.test(v);}); }
  function templateShape(templates){ var names=Object.keys(TEMPLATE_TOKENS).sort(), got,i,row; if(!templates||typeof templates!=='object'||Object.keys(templates).sort().join('|')!==names.join('|')) return false; for(i=0;i<names.length;i++){row=templates[names[i]]; if(!row||!exact(row,['text','tokens'])||!text(row.text)||!Array.isArray(row.tokens)||row.tokens.join('|')!==TEMPLATE_TOKENS[names[i]].join('|')) return false;} return true; }
  function snapshotShape(value,audience){ return value&&exact(value,['schemaVersion','audience','revision','projectionDigest','rotationEditionV2','selectionKeys','resolutionRecords','blockedKeys'])&&value.schemaVersion===1&&value.audience===audience&&DIGEST.test(value.revision)&&DIGEST.test(value.projectionDigest)&&(value.rotationEditionV2==='enabled'||value.rotationEditionV2==='disabled')&&Array.isArray(value.selectionKeys)&&Array.isArray(value.resolutionRecords)&&Array.isArray(value.blockedKeys); }
  function prepare(projection,expectedAudience,subtle){
    var value,records={},selection={},blocked={},i,record,bare,projectionBare;
    if(expectedAudience!=='ms3'&&expectedAudience!=='resident') return Promise.resolve({ok:false,snapshot:null,errors:[failure()]});
    try{value=copy(projection);}catch(ignoreCopy){return Promise.resolve({ok:false,snapshot:null,errors:[failure()]});}
    if(!snapshotShape(value,expectedAudience)||value.resolutionRecords.length>MAX||value.selectionKeys.length>MAX||value.blockedKeys.length>MAX) return Promise.resolve({ok:false,snapshot:null,errors:[failure('CATALOG_SNAPSHOT') ]});
    for(i=0;i<value.resolutionRecords.length;i++){record=value.resolutionRecords[i]; if(!recordShape(record)||record.audiences.indexOf(expectedAudience)<0||records[record.key]) return Promise.resolve({ok:false,snapshot:null,errors:[failure('CATALOG_RECORD')]}); bare=copy(record); delete bare.contentDigest; records[record.key]=record;}
    for(i=0;i<value.selectionKeys.length;i++){ if(!KEY.test(value.selectionKeys[i])||selection[value.selectionKeys[i]]||!records[value.selectionKeys[i]]) return Promise.resolve({ok:false,snapshot:null,errors:[failure('CATALOG_SELECTION')]}); selection[value.selectionKeys[i]]=true; }
    for(i=0;i<value.blockedKeys.length;i++){ if(!KEY.test(value.blockedKeys[i])||blocked[value.blockedKeys[i]]||records[value.blockedKeys[i]]) return Promise.resolve({ok:false,snapshot:null,errors:[failure('CATALOG_BLOCKED')]}); blocked[value.blockedKeys[i]]=true; }
    projectionBare=copy(value); delete projectionBare.projectionDigest;
    return Promise.all(value.resolutionRecords.map(function(item){var bareRecord=copy(item); delete bareRecord.contentDigest; return digest(bareRecord,subtle).then(function(actual){if(actual!==item.contentDigest) throw Error('digest');});}).concat([digest(projectionBare,subtle).then(function(actual){if(actual!==value.projectionDigest) throw Error('digest');})])).then(function(){ var trusted=frozen(value); branded.add(trusted); privateIndex.set(trusted,{records:records,selection:selection,blocked:blocked}); return {ok:true,snapshot:trusted,errors:[]};},function(){return {ok:false,snapshot:null,errors:[failure('CATALOG_DIGEST')]};});
  }
  function recordFor(snapshot,key,mode,kind,location){ var index,record; if(!branded.has(snapshot)||!KEY.test(key)||!KEY.test(location)||(mode!=='builder'&&mode!=='learner')) return {ok:false,record:null,error:'CATALOG_UNAVAILABLE'}; index=privateIndex.get(snapshot); if(index.blocked[key]) return {ok:false,record:null,error:'CATALOG_BLOCKED'}; record=index.records[key]; if(!record||record.kind!==kind) return {ok:false,record:null,error:'CATALOG_UNAVAILABLE'}; if(mode==='builder'&&!index.selection[key]) return {ok:false,record:null,error:'CATALOG_RESELECTION_REQUIRED'}; if(record.kind!=='trainingLocation'&&record.locationKeys&&record.locationKeys.indexOf(location)<0) return {ok:false,record:null,error:'CATALOG_UNAVAILABLE'}; if(record.kind==='trainingLocation'&&record.key!==location) return {ok:false,record:null,error:'CATALOG_UNAVAILABLE'}; return {ok:true,record:frozen(copy(record)),error:''}; }
  function contextValue(value){ var copyValue; try{copyValue=copy(value);}catch(ignore){return null;} if(!copyValue||!exact(copyValue,['audience','localCatalogRevision','rotationEditionV2','coreRevision'])) return null; return copyValue; }
  function label(priority){ return {required:'Required',recommended:'Recommended',optional:'Optional'}[priority]||''; }
  function list(values){ if(values.length===1)return values[0]; if(values.length===2)return values[0]+' and '+values[1]; return values.slice(0,-1).join(', ')+', and '+values[values.length-1]; }
  function displayTime(value){ var hour=Number(value.slice(0,2)),minute=value.slice(3),suffix=hour<12?'AM':'PM'; hour=hour%12||12; return hour+':'+minute+' '+suffix; }
  function dateText(value){ var months=['January','February','March','April','May','June','July','August','September','October','November','December'],p=value.split('-'); return months[Number(p[1])-1]+' '+Number(p[2])+', '+p[0]; }
  function render(template,values){ var tokens,output,i,key; if(!template||!Array.isArray(template.tokens)||!TEMPLATE_TOKENS[key]){} tokens=template.tokens; output=template.text; for(i=0;i<tokens.length;i++){key=tokens[i]; if(!own.call(values,key)||!text(String(values[key]))) throw Error('template'); output=output.replace('{'+key+'}',values[key]);} if(/[{}<>]/.test(output)) throw Error('template'); return output; }
  function linkView(record){ return {title:record.title,url:record.url,visibleHostname:record.visibleHostname,purposeCode:record.purposeCode}; }
  function usable(snapshot,key,mode,kind,location,choiceKind){ var result=recordFor(snapshot,key,mode,kind,location); if(!result.ok) throw Error(result.error); if(choiceKind&&result.record.choiceKind!==choiceKind) throw Error('kind'); return result.record; }
  function resolve(config,snapshot,mode,siteContext,subtle){
    var value,context,location,curator,role,phrases,index,refs={},model,pathId,labels,plan,i,item,reason;
    if(!branded.has(snapshot)) return Promise.resolve({ok:false,resolved:null,referenceSetDigest:'',displayModel:null,errors:[failure()]});
    try{value=copy(config);context=contextValue(siteContext);}catch(ignore){return Promise.resolve({ok:false,resolved:null,referenceSetDigest:'',displayModel:null,errors:[failure()]});}
    if(!context||context.audience!==snapshot.audience||context.localCatalogRevision!==snapshot.revision||context.rotationEditionV2!==snapshot.rotationEditionV2||!CORE.test(context.coreRevision)||!value||value.audience!==snapshot.audience||!value.context||!value.localPlan) return Promise.resolve({ok:false,resolved:null,referenceSetDigest:'',displayModel:null,errors:[failure()]});
    pathId=value.pathId; labels=pathId==='ms3-six-week'&&value.audience==='ms3'?['MS3','6 weeks']:pathId==='resident-four-week'&&value.audience==='resident'?['Resident','4 weeks']:null; if(!labels||!value.context||!KEY.test(value.context.trainingLocationKey)||!KEY.test(value.context.curatorProfileKey)||!KEY.test(value.phraseSetKey)||!Array.isArray(value.pathItems)||!CORE.test(value.createdAgainstCoreRevision)||!DIGEST.test(value.createdAgainstLocalCatalogRevision)||!DATE.test(value.context.rotationStart)||!DATE.test(value.context.rotationEnd)||!DATE.test(value.context.editionCheckedOn)||typeof value.editionNumber!=='number') return Promise.resolve({ok:false,resolved:null,referenceSetDigest:'',displayModel:null,errors:[failure()]});
    try{
      location=usable(snapshot,value.context.trainingLocationKey,mode,'trainingLocation',value.context.trainingLocationKey); refs[location.key]=location.contentDigest;
      curator=usable(snapshot,value.context.curatorProfileKey,mode,'curatorProfile',location.key); refs[curator.key]=curator.contentDigest;
      role=usable(snapshot,curator.roleKey,mode,'choice',location.key,'role'); refs[role.key]=role.contentDigest;
      phrases=usable(snapshot,value.phraseSetKey,mode,'phraseSet',location.key); refs[phrases.key]=phrases.contentDigest;
      model={card:{title:location.locationCode+' '+labels[0]+' psychiatry rotation',locationName:location.displayName,locationCode:location.locationCode,locationTypeLabel:{inpatient:'Inpatient',outpatient:'Outpatient','consult-liaison':'Consult-liaison',emergency:'Emergency',community:'Community',mixed:'Mixed'}[location.locationTypeCode],curatorName:curator.displayName,curatorRole:role.fragment,audienceLabel:labels[0],durationLabel:labels[1],rotationDates:dateText(value.context.rotationStart)+' – '+dateText(value.context.rotationEnd),editionCheckedOn:dateText(value.context.editionCheckedOn),editionCheckedOnLabel:'Self-attested',editionNumber:value.editionNumber,fingerprintPrefix:location.locationCode+'-'+(value.audience==='ms3'?'MS3':'RES')+'-',fingerprint:'',identityNotice:'Curator identity and institutional endorsement are not digitally verified by this link.',fingerprintNotice:'Compare this fingerprint with the curator. Matching codes confirm the same edition content, not identity or institutional approval.',provenance:[{recordKind:'trainingLocation',displayLabel:location.displayName,verifiedOn:location.verifiedOn},{recordKind:'curatorProfile',displayLabel:curator.displayName,verifiedOn:curator.verifiedOn},{recordKind:'phraseSet',displayLabel:phrases.displayName,verifiedOn:phrases.verifiedOn}]},revisions:{createdAgainstCoreRevision:value.createdAgainstCoreRevision,currentCoreRevision:context.coreRevision,coreMatches:value.createdAgainstCoreRevision===context.coreRevision,createdAgainstCatalogRevision:value.createdAgainstLocalCatalogRevision,currentCatalogRevision:snapshot.revision,catalogMatches:value.createdAgainstLocalCatalogRevision===snapshot.revision},pathItems:[],firstDay:{arrival:null,accessItems:[],contacts:[],checklistItems:[]},typicalDay:null,workflow:{rounds:null,presentation:null,documentation:null},attendanceFeedback:{attendance:null,feedback:null},resources:[],authority:copy(AUTHORITY),changeSummary:{kindCodes:value.changeSummary&&Array.isArray(value.changeSummary.kindCodes)?value.changeSummary.kindCodes.slice():[],changedItemCount:value.changeSummary&&typeof value.changeSummary.changedItemCount==='number'?value.changeSummary.changedItemCount:0,text:'',provenanceLabel:'Locally supplied edition summary; change lineage is not authenticated.'},emptyLocalPlan:Object.keys(value.localPlan).length===0};
      for(i=0;i<value.pathItems.length;i++){item=value.pathItems[i]; if(!item||!KEY.test(item.reasonKey)||typeof item.instanceId!=='string'||typeof item.ref!=='string'||typeof item.week!=='number'||typeof item.order!=='number'||!label(item.priority)) throw Error('path'); reason=usable(snapshot,item.reasonKey,mode,'choice',location.key,'reason'); refs[reason.key]=reason.contentDigest; model.pathItems.push({instanceId:item.instanceId,ref:item.ref,week:item.week,order:item.order,priority:item.priority,priorityLabel:label(item.priority),reasonText:reason.fragment});}
      plan=value.localPlan; resolvePlan(plan,phrases,location.key,snapshot,mode,refs,model);
      index=Object.keys(refs).sort().map(function(key){return [key,refs[key]];});
    }catch(ignoreResolve){return Promise.resolve({ok:false,resolved:null,referenceSetDigest:'',displayModel:null,errors:[failure()]});}
    return digest(index,subtle).then(function(referenceSetDigest){return {ok:true,resolved:frozen({config:frozen(copy(value)),location:frozen(copy(location)),curator:frozen(copy(curator)),phraseSet:frozen(copy(phrases))}),referenceSetDigest:referenceSetDigest,displayModel:frozen(model),errors:[]};},function(){return {ok:false,resolved:null,referenceSetDigest:'',displayModel:null,errors:[failure()]};});
  }
  function resolvePlan(plan,phrases,location,snapshot,mode,refs,model){
    var arrival,place,role,link,rows,i,row,item,due,priority,choice,events=[];
    function get(key,kind,choiceKind){var record=usable(snapshot,key,mode,kind,location,choiceKind); refs[record.key]=record.contentDigest; return record;}
    function template(name,values){return render(phrases.templates[name],values);}
    function addLink(record){model.card.provenance.push({recordKind:'officialLink',displayLabel:record.title,verifiedOn:record.verifiedOn}); return linkView(record);}
    if(plan.arrival){arrival=plan.arrival; place=get(arrival.placeKey,'place'); role=get(arrival.checkInRoleKey,'choice','role'); model.firstDay.arrival={text:template('arrival',{timing:arrival.timingCode,time:displayTime(arrival.time),place:place.displayName,role:role.fragment})}; if(arrival.linkKey){link=get(arrival.linkKey,'officialLink');model.firstDay.arrival.link=addLink(link);} model.firstDay.checklistItems.push({id:'local:generated:arrival',text:model.firstDay.arrival.text,priority:'required',priorityLabel:'Required',sourceCode:'arrival'});}
    if(plan.schedule){rows=plan.schedule.events||[]; for(i=0;i<rows.length;i++){row=rows[i]; choice=get(row.daySetKey,'choice','daySet');item=get(row.activityKey,'choice','activity');priority=label(row.priority); if(row.placeKey){place=get(row.placeKey,'place');} modelTextEvent(row,choice,item,place,priority,template,events);} model.typicalDay={summaryText:template('scheduleWindow',{dayStart:displayTime(plan.schedule.dayStart),dayEnd:displayTime(plan.schedule.dayEnd),endQualifier:{at:'at',about:'about','no-later-than':'no later than'}[plan.schedule.endQualifierCode]}),eventItems:events};}
    if(plan.rounds){model.workflow.rounds={text:template('rounds',{preparation:get(plan.rounds.preparationKey,'choice','roundsPreparation').fragment,participation:get(plan.rounds.participationKey,'choice','roundsParticipation').fragment,followUp:get(plan.rounds.followUpKey,'choice','roundsFollowUp').fragment})};}
    if(plan.presentation){model.workflow.presentation={text:template('presentation',{format:get(plan.presentation.formatKey,'choice','presentationFormat').fragment,timing:get(plan.presentation.timingKey,'choice','presentationTiming').fragment,elements:list((plan.presentation.elementKeys||[]).map(function(key){return get(key,'choice','presentationElement').fragment;}))})};}
    if(plan.documentation){model.workflow.documentation={text:template('documentation',{workflow:get(plan.documentation.workflowKey,'choice','documentationWorkflow').fragment,timing:get(plan.documentation.timingKey,'choice','documentationTiming').fragment}),guardrailText:AUTHORITY.documentationGuardrail}; if(plan.documentation.policyLinkKey) model.workflow.documentation.link=addLink(get(plan.documentation.policyLinkKey,'officialLink'));}
    if(plan.attendance){model.attendanceFeedback.attendance={text:template('attendance',{events:list((plan.attendance.eventInstanceIds||[])),absenceRole:get(plan.attendance.absenceRoleKey,'choice','role').fragment})}; if(plan.attendance.policyLinkKey) model.attendanceFeedback.attendance.link=addLink(get(plan.attendance.policyLinkKey,'officialLink'));}
    if(plan.feedback){model.attendanceFeedback.feedback={text:template('feedback',{cadence:get(plan.feedback.cadenceKey,'choice','feedbackCadence').fragment,initiator:get(plan.feedback.initiatorKey,'choice','feedbackInitiator').fragment,setting:get(plan.feedback.settingKey,'choice','feedbackSetting').fragment})};}
    rows=plan.accessItems||[]; for(i=0;i<rows.length;i++){row=rows[i];item=get(row.itemKey,'choice','accessItem');due=get(row.dueKey,'choice','duePoint');model.firstDay.accessItems.push({id:row.instanceId,text:template('access',{item:item.fragment,due:due.fragment}),checklistId:'local:generated:access:'+row.instanceId}); if(row.linkKey)model.firstDay.accessItems[model.firstDay.accessItems.length-1].link=addLink(get(row.linkKey,'officialLink'));model.firstDay.checklistItems.push({id:'local:generated:access:'+row.instanceId,text:model.firstDay.accessItems[model.firstDay.accessItems.length-1].text,priority:'required',priorityLabel:'Required',sourceCode:'access'});}
    rows=plan.contacts||[]; for(i=0;i<rows.length;i++){row=rows[i];model.firstDay.contacts.push({id:row.instanceId,text:template('contact',{role:get(row.roleKey,'choice','role').fragment})});if(row.linkKey)model.firstDay.contacts[model.firstDay.contacts.length-1].link=addLink(get(row.linkKey,'officialLink'));}
    rows=plan.checklistItems||[]; for(i=0;i<rows.length;i++){row=rows[i];priority=label(row.priority);model.firstDay.checklistItems.push({id:row.instanceId,text:template('checklist',{item:get(row.itemKey,'choice','checklist').fragment,priority:priority}),priority:row.priority,priorityLabel:priority,sourceCode:'selected'});}
    rows=plan.resources||[]; for(i=0;i<rows.length;i++){row=rows[i];link=get(row.linkKey,'officialLink');priority=label(row.priority);choice=row.reasonKey?get(row.reasonKey,'choice','reason'):null;model.resources.push({id:row.instanceId,text:template(choice?'resourceWithReason':'resourceWithoutReason',choice?{title:link.title,priority:priority,week:String(row.week),reason:choice.fragment,hostname:link.visibleHostname}:{title:link.title,priority:priority,week:String(row.week),hostname:link.visibleHostname}),title:link.title,url:link.url,visibleHostname:link.visibleHostname,purposeCode:link.purposeCode,priority:row.priority,priorityLabel:priority,week:row.week,authorityLabel:AUTHORITY.resourceLabel});if(choice)model.resources[model.resources.length-1].reasonText=choice.fragment;addLink(link);}
  }
  function modelTextEvent(row,day,activity,place,priority,template,events){var name=row.endTime?(place?'scheduleRangeWithPlace':'scheduleRangeWithoutPlace'):(place?'schedulePointWithPlace':'schedulePointWithoutPlace'),values={daySet:day.fragment,startTime:displayTime(row.startTime),activity:activity.fragment,priority:priority};if(row.endTime)values.endTime=displayTime(row.endTime);if(place)values.place=place.displayName;events.push({id:row.instanceId,text:template(name,values),priority:row.priority,priorityLabel:priority});}
  return {snapshot:prepare,record:recordFor,resolve:resolve,enabled:function(snapshot){return branded.has(snapshot)&&snapshot.rotationEditionV2==='enabled';}};
}());
var fdEditionCatalogSnapshot=FD_EDITION_CATALOG.snapshot;
var fdEditionCatalogRecord=FD_EDITION_CATALOG.record;
var fdEditionCatalogResolve=FD_EDITION_CATALOG.resolve;
var fdEditionPublicationEnabled=FD_EDITION_CATALOG.enabled;
