import test from 'node:test';
import assert from 'node:assert/strict';
import {buildEvidenceSources,reviewSchema,isReviewSchema,validateReviewSources,validateDebrief} from '../lib/moments/evidence.mjs';
const observations={E_MISMATCH:['earlier_miss_addressed','positive_reframe_repeated'],E_MEANING:['rent_meaning_explored'],E_PATIENT_FOCUS:['attention_returned','reassurance_requested'],E_BOUNDARY:['pause_respected','questioning_after_pause'],E_ASSURANCE:['outcome_promised'],P_CONCERN:['concern_retained','concern_distorted'],P_INVITATION:['correction_invited'],P_REVISION:['correction_carried_forward','correction_not_carried'],P_RETENTION:['accurate_account_retained'],P_ATTRIBUTION:['fear_kept_as_fear','unestablished_effect_asserted'],P_UNCERTAINTY:['unknown_history_preserved'],L_STATUS:['pending_status_explained','booking_asserted'],L_INVITATION:['own_words_invited'],L_REPAIR:['misunderstanding_addressed'],L_RECHECK:['understanding_demonstrated','understanding_not_demonstrated'],L_FEASIBILITY:['barrier_recognized','barrier_answered_with_repetition'],L_LIMITS:['next_step_bounded','logistics_promised']};
const fallbacks=['not_assessable','transcription_uncertain','simulation_drift','specific_opportunity_unanswered'];
function def(prefix='P') {const criteria=Object.entries(observations).filter(([id])=>id.startsWith(prefix)).map(([id,observationIds])=>({id,observationIds}));return {id:`moment_${prefix}`,learner:{setup:'An earlier student said something.',setupAttribution:prefix==='E'?'Previous student — scripted':''},criteria,allowedUncertaintyIds:['insufficient_evidence','capture_uncertain','treatment_history_unknown'],allowedNextAttemptIds:['reflect'],templates:{observations:Object.fromEntries([...criteria.flatMap(c=>c.observationIds),...fallbacks].map(id=>[id,`Authored ${id}.`])),uncertainties:{insufficient_evidence:'This exchange does not establish the missing detail.',capture_uncertain:'The captured words need clarification.',treatment_history_unknown:'Current or previous treatment experience has not been established here.',simulation_fact_uncertain:'The simulated patient statement is inconsistent with the authored scenario.'},nextAttempts:{reflect:'Reflect on this wording.'}}};}
const source=(id,text=id,uncertain=false)=>({id,kind:id==='setup'?'scripted_setup':id==='team-summary'?'team_formulation':id[0]==='p'?'patient_heard':'learner',speaker:id==='setup'?'setup':id[0]==='p'?'patient':'learner',text,turn:['setup','team-summary'].includes(id)?null:Number(id.slice(1)),uncertain});
const sources=()=>['p0','l1','p1','l2','p2','team-summary'].map(id=>source(id));
const cite=s=>({sourceId:s.id,start:0,end:s.text.length,quote:s.text});
function report(criterionId,observationId,ss,status='observed',uncertaintyId='insufficient_evidence') {return {schemaVersion:1,scenarioId:`moment_${criterionId[0]}`,findings:[{criterionId,status,observationId,evidence:ss.map(cite),uncertaintyId,nextAttemptId:'reflect'}]};}
const check=(r,ss,d=def(r.scenarioId.at(-1)),options={endReason:'learner_end'})=>validateDebrief(r,ss,d,options);
test('source IDs follow actual history positions and only finalized heard patient text survives',()=>{const history=[{who:'pt',text:'Opening unheard',playbackStatus:'interrupted'},{who:'me',text:'You do not want help.'},{who:'pt',text:'I want help. The rest was not heard.',playbackStatus:'interrupted'},{who:'me',text:'Thanks.'},{who:'pt',text:'Heard prefix.',playbackStatus:'played',omittedTail:true}];const ss=buildEvidenceSources(def(),history,{teamFormulation:'A tentative summary.',summaryUncertain:true,uncertainTurnIds:[1]});assert.deepEqual(ss.map(s=>s.id),['setup','l1','l2','p2','team-summary']);assert.equal(ss[1].uncertain,true);assert.equal(ss.at(-1).uncertain,true);assert.equal(ss.find(s=>s.id==='p2').text,'Heard prefix.');assert.equal(ss.some(s=>s.text.includes('not heard')),false);});
test('setup preserves previous student attribution separately',()=>{assert.equal(buildEvidenceSources(def('E'),[],{})[0].speaker,'previous_student');assert.equal(buildEvidenceSources(def(),[],{})[0].speaker,'setup');});
test('malformed or oversized sources are rejected',()=>{for(const mutate of [s=>s.push({...s[0]}),s=>s[0].speaker='learner',s=>s[0].id='private-fact',s=>s[0].extra=true,s=>s[0].text='a'.repeat(2001),s=>s[0].text='bad\ntext',s=>s[0].turn=4,s=>s.reverse()]) {const ss=sources();mutate(ss);assert.throws(()=>validateReviewSources(ss));}assert.throws(()=>validateReviewSources(Array.from({length:12},()=>source('p0'))));assert.throws(()=>validateReviewSources(['setup','p0','l1','p1','l2','p2','l3','p3','l4','p4','team-summary'].map(id=>source(id,'a'.repeat(2000)))));});
test('schema is strict and only immutable server-generated schema is trusted',()=>{const schema=reviewSchema(def());assert.equal(isReviewSchema(schema),true);assert.equal(isReviewSchema(JSON.parse(JSON.stringify(schema))),false);assert.throws(()=>{schema.properties.scenarioId.const='forged';});const walk=o=>{if(!o||typeof o!=='object')return;if(o.type==='object'){assert.equal(o.additionalProperties,false);assert.deepEqual([...o.required].sort(),Object.keys(o.properties).sort());}Object.values(o).forEach(walk);};walk(schema);assert.ok(Buffer.byteLength(JSON.stringify(schema))<=32768);});
test('Priya revision requires before, heard correction, after in chronological order',()=>{const ss=sources();const chain=[ss[1],ss[2],ss[5]];const r=report('P_REVISION','correction_carried_forward',chain);assert.equal(check(r,ss).findings[0].observationText,'Authored correction_carried_forward.');for(const bad of [[ss[1],ss[5]],[ss[0],ss[1],ss[5]],[ss[3],ss[2],ss[5]],[ss[1],ss[2],ss[1]]])assert.throws(()=>check(report('P_REVISION','correction_carried_forward',bad),ss));assert.doesNotThrow(()=>check(report('P_REVISION','correction_not_carried',chain),ss));});
test('accurate retention requires first account, confirmation and explicit team formulation',()=>{const ss=sources();assert.doesNotThrow(()=>check(report('P_RETENTION','accurate_account_retained',[ss[1],ss[2],ss[5]]),ss));assert.throws(()=>check(report('P_RETENTION','accurate_account_retained',[ss[1],ss[2],ss[3]]),ss));});
test('all appendix evidence chains enforce source role and ordering',()=>{const ss=[source('setup'),...sources()];const by=Object.fromEntries(ss.map(s=>[s.id,s]));by.setup.speaker='previous_student';const cases=[['E_MISMATCH','earlier_miss_addressed',['setup','l1']],['E_MISMATCH','positive_reframe_repeated',['p0','l1']],['E_MEANING','rent_meaning_explored',['l1','p1']],['E_PATIENT_FOCUS','attention_returned',['l1']],['E_PATIENT_FOCUS','reassurance_requested',['l1']],['E_BOUNDARY','pause_respected',['p0','l1']],['E_BOUNDARY','questioning_after_pause',['p0','l1']],['E_ASSURANCE','outcome_promised',['l1']],['P_CONCERN','concern_retained',['p0','l1']],['P_CONCERN','concern_distorted',['p0','l1']],['P_INVITATION','correction_invited',['l1']],['P_ATTRIBUTION','fear_kept_as_fear',['p0','team-summary']],['P_ATTRIBUTION','unestablished_effect_asserted',['team-summary']],['P_UNCERTAINTY','unknown_history_preserved',['team-summary']],['L_STATUS','pending_status_explained',['setup','l1']],['L_STATUS','booking_asserted',['setup','l1']],['L_INVITATION','own_words_invited',['l1']],['L_REPAIR','misunderstanding_addressed',['p0','l1']],['L_RECHECK','understanding_demonstrated',['p0','l1','p1']],['L_RECHECK','understanding_not_demonstrated',['l1','p1'],'unclear'],['L_FEASIBILITY','barrier_recognized',['p0','l1']],['L_FEASIBILITY','barrier_answered_with_repetition',['p0','l1']],['L_LIMITS','next_step_bounded',['l1']],['L_LIMITS','logistics_promised',['l1']]];for(const [criterion,observation,ids,status] of cases){assert.doesNotThrow(()=>check(report(criterion,observation,ids.map(id=>by[id]),status),ss),observation);assert.throws(()=>check(report(criterion,observation,[by.p1],status),ss),observation);}});
test('stopping is never evidence of a missing opportunity',()=>{const ss=sources();for(const endReason of ['learner_end','technical_interruption','turn_limit']){assert.throws(()=>check(report('P_INVITATION','specific_opportunity_unanswered',[ss[1]],'opportunity_not_taken'),ss,def(),{endReason}));assert.doesNotThrow(()=>check(report('P_INVITATION','specific_opportunity_unanswered',[ss[0],ss[1]],'opportunity_not_taken'),ss,def(),{endReason}));}});
test('uncertain consequential source cannot support positive or negative substantive claims',()=>{const ss=sources();ss.at(-1).uncertain=true;for(const id of ['correction_carried_forward','correction_not_carried'])assert.throws(()=>check(report('P_REVISION',id,[ss[1],ss[2],ss[5]]),ss));assert.throws(()=>check(report('P_REVISION','correction_carried_forward',[ss[1],ss[2],ss[3]]),ss),'uncertain team summary cannot be bypassed with an earlier formulation');assert.doesNotThrow(()=>check(report('P_REVISION','transcription_uncertain',[ss[5]],'unclear','capture_uncertain'),ss));assert.throws(()=>check(report('P_REVISION','transcription_uncertain',[ss[1]],'unclear','capture_uncertain'),ss));});
test('simulation drift cites heard actor source and preserves reference-fact uncertainty even when learner repeats it',()=>{const ss=[source('p0','My new medication caused this.'),source('l1','Your new medication caused this.')];const r=report('P_ATTRIBUTION','simulation_drift',[ss[0]],'not_assessable','simulation_fact_uncertain');const dto=check(r,ss);assert.equal(dto.findings[0].uncertaintyText,'The simulated patient statement is inconsistent with the authored scenario.');assert.throws(()=>check(report('P_ATTRIBUTION','simulation_drift',[ss[1]],'not_assessable','simulation_fact_uncertain'),ss));assert.throws(()=>check(report('P_ATTRIBUTION','unestablished_effect_asserted',[ss[1]],'observed','simulation_fact_uncertain'),ss));});
test('strict report rejects any invalid finding, fields, template, status or quote',()=>{const ss=sources();const good=report('P_INVITATION','correction_invited',[ss[1]]);for(const mutate of [r=>r.extra='HTML',r=>r.findings[0].html='<b>Good</b>',r=>r.findings[0].score=1,r=>r.findings[0].criterionId='L_STATUS',r=>r.findings[0].observationId='fear_kept_as_fear',r=>r.findings[0].uncertaintyId='trust_unknown',r=>r.findings[0].status='opportunity_not_taken',r=>r.findings[0].evidence[0].quote='fabricated',r=>r.findings[0].evidence[0].sourceId='private-fact',r=>r.findings[0].evidence[0].speaker='learner',r=>r.findings.push({...r.findings[0]}),r=>r.findings.push(...Array(3).fill(r.findings[0]))]){const r=structuredClone(good);mutate(r);assert.throws(()=>check(r,ss));}const r=structuredClone(good);r.findings.push({...r.findings[0],criterionId:'P_CONCERN',observationId:'concern_retained'});assert.throws(()=>check(r,ss),'one bad finding fails the entire report');});
test('UTF-16 offsets are exact and cannot split surrogate pairs or exceed quote bounds',()=>{const ss=[source('l1','A 😀 quoted invitation.')];const r=report('P_INVITATION','correction_invited',ss);r.findings[0].evidence=[{sourceId:'l1',start:2,end:4,quote:'😀'}];assert.doesNotThrow(()=>check(r,ss));for(const [start,end] of [[2,3],[3,4],[-1,2],[0,999],[0,0],[0.5,2]]) {const bad=structuredClone(r);bad.findings[0].evidence=[{sourceId:'l1',start,end,quote:ss[0].text.slice(start,end)}];assert.throws(()=>check(bad,ss));}const long=[source('l1','a'.repeat(301))];assert.throws(()=>check(report('P_INVITATION','correction_invited',long),long));});
test('uncited missing or uncertain evidence cannot be laundered into substantive assessment',()=>{const ss=sources();ss[2].uncertain=true;assert.throws(()=>check(report('P_REVISION','correction_carried_forward',[ss[1],ss[2],ss[5]]),ss));const r=report('P_REVISION','not_assessable',[],'not_assessable');assert.doesNotThrow(()=>check(r,ss));assert.throws(()=>check({...r,findings:[{...r.findings[0],status:'observed'}]},ss));});
test('authored catalog integrates with bounded schema, sources and fallback templates',async()=>{const {momentIds,getMoment}=await import('../lib/moments/catalog.mjs');for(const id of momentIds){const d=getMoment(id);const ss=buildEvidenceSources(d,[{who:'pt',text:d.opening,playbackStatus:'played'}]);assert.equal(ss[0].text,d.learner.setup);assert.equal(ss[1].text,d.opening);assert.equal(isReviewSchema(reviewSchema(d)),true);const r={schemaVersion:1,scenarioId:id,findings:[{criterionId:d.criteria[0].id,status:'not_assessable',observationId:'not_assessable',evidence:[],uncertaintyId:'insufficient_evidence',nextAttemptId:'reflect'}]};const dto=validateDebrief(r,ss,d,{endReason:'learner_end'});assert.equal(dto.findings[0].observationText,d.templates.observations.not_assessable);assert.deepEqual(Object.keys(dto),['schemaVersion','scenarioId','findings']);assert.equal(JSON.stringify(dto).includes('fixedFacts'),false);}});
test('exact utterance containing markup stays quote data, with no model-authored HTML field',()=>{const ss=[source('l1','<img src=x onerror=alert(1)> Can you correct me?')];const dto=check(report('P_INVITATION','correction_invited',ss),ss);assert.equal(dto.findings[0].evidence[0].quote,ss[0].text);assert.equal(Object.hasOwn(dto.findings[0],'html'),false);});
test('four citations per finding and 1200 total UTF-16 units are hard bounds',()=>{const ss=sources().map(s=>({...s,text:'a'.repeat(300)}));const r=report('P_REVISION','correction_carried_forward',[ss[1],ss[2],ss[3],ss[5]]);assert.doesNotThrow(()=>check(r,ss));r.findings.push(report('P_INVITATION','correction_invited',[ss[1]]).findings[0]);assert.throws(()=>check(r,ss));const tooMany=report('P_REVISION','correction_carried_forward',ss);assert.throws(()=>check(tooMany,ss));});
test('source construction rejects forged uncertainty indices and malformed history',()=>{const history=[{who:'pt',text:'Hello.',playbackStatus:'played'},{who:'me',text:'My reply.'}];for(const options of [{uncertainTurnIds:[2]},{uncertainTurnIds:[1,1]},{uncertainTurnIds:[2,1]},{summaryUncertain:true},{teamFormulation:'a'.repeat(1201)}])assert.throws(()=>buildEvidenceSources(def(),history,options));assert.throws(()=>buildEvidenceSources(def(),[{who:'me',text:'I should not be the opening.'}]));});
test('all frozen challenge expectations have valid attributed evidence and authored templates',async()=>{const {readFile}=await import('node:fs/promises');const {getMoment}=await import('../lib/moments/catalog.mjs');const {challenges}=JSON.parse(await readFile(new URL('./fixtures/moments/challenges.json',import.meta.url),'utf8'));assert.equal(challenges.length,39);let findings=0;for(const c of challenges)for(const f of c.expected){const r={schemaVersion:1,scenarioId:c.scenarioId,findings:[f]};assert.doesNotThrow(()=>validateDebrief(r,c.sources,getMoment(c.scenarioId),{endReason:c.endReason}),`${c.id}: ${f.observationId}`);findings++;}assert.ok(findings>=39);});
