import {mkdir,rm,copyFile,readdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const here=path.dirname(fileURLToPath(import.meta.url));
const allowed=['index.html','app.js','styles.css'];
const publicFiles=(await readdir(path.join(here,'public'))).sort();
if(JSON.stringify(publicFiles)!==JSON.stringify([...allowed].sort()))throw new Error('Preview public directory differs from the explicit allowlist.');
await rm(path.join(here,'dist'),{recursive:true,force:true});
await mkdir(path.join(here,'dist'));
for(const file of allowed)await copyFile(path.join(here,'public',file),path.join(here,'dist',file));
console.log('Built three public preview assets; private case and server sources excluded.');
