#!/usr/bin/env python3
"""Quarterly APA refresh: re-curate crosswalk, rebuild catalog.html, diff vs prior crawl.
Run from anywhere. Pure-Python, no network. The actual re-crawl is the separate
Chrome-based download_public_apa_resources.py (run attended)."""
import csv,re,os,glob,json,sys
# Portable: this script lives in 13_Faculty_Resources/APA_Downloads_*/scripts/,
# so the faculty dir is two levels up — derive it, no hard-coded machine paths.
FAC=os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
sets=sorted(glob.glob(os.path.join(FAC,"APA_Downloads_*")))
sets=[s for s in sets if os.path.isdir(s)]
if not sets: sys.exit("no APA_Downloads_* set found")
CUR=sets[-1]; PREV=sets[-2] if len(sets)>1 else None
md=os.path.join(CUR,"metadata")
def norm(s):
    s=re.sub(r'\.(pdf|pptx|docx)$','',s,flags=re.I); s=re.sub(r'^APA[-_]','',s)
    s=re.sub(r'DSM[-_]?5[-_]?TR','',s,flags=re.I); s=re.sub(r'DSM[-_]?5','',s,flags=re.I)
    return re.sub(r'[^a-z0-9]','',s.lower())
SECTION_FIX={'tdah-folleto.pdf':'14_Tracks/Patients_Families (Spanish)',
 'APA-CDC-Perinatal-Mental-and-Substance-Use-Disorders-Whitepaper.pdf':'03_Core_Topics/Perinatal',
 '3-20-26-Hispanic-Population-MH-Handout.pdf':'10_Patient_and_Family_Education (+ Diversity)'}
# ---- re-curate from library_crosswalk.csv (regenerated by the crawler/categorizer) ----
xw=os.path.join(md,"library_crosswalk.csv")
if not os.path.exists(xw): sys.exit("library_crosswalk.csv missing — re-run the categorizer after a fresh crawl")
rows=list(csv.DictReader(open(xw)))
tr={norm(r['clean_title']):r['clean_title'] for r in rows
    if not r['decision'].startswith('ARCHIVE') and ('DSM5TR' in r['local_file'] or 'DSM-5-TR' in r['clean_title'])}
out=[]
for r in rows:
    dec=r['decision']
    disp=('SURFACE' if dec.startswith('SURFACE') else 'BACKGROUND' if dec.startswith('BACKGROUND')
          else 'CATALOG' if not dec.startswith('ARCHIVE')
          else ('STALE' if ('stale' in dec.lower() or 'icd' in r['clean_title'].lower() or 'update' in r['clean_title'].lower()) else 'SUPERSEDED'))
    out.append({'clean_title':r['clean_title'],'category':r['category_codex'],
        'section':SECTION_FIX.get(r['clean_title'],r['target_section']),'disposition':disp,
        'local_file':r['local_file'],'apa_source_url':r['apa_source_url'],'bytes':r['bytes'],
        'superseded_by':tr.get(norm(r['clean_title']),'') if disp=='SUPERSEDED' else ''})
with open(os.path.join(md,"library_crosswalk_curated.csv"),'w',newline='') as f:
    w=csv.DictWriter(f,fieldnames=list(out[0].keys())); w.writeheader(); w.writerows(out)
json.dump(out,open(os.path.join(md,"catalog_data.json"),'w'),ensure_ascii=False)
tpl=open(os.path.join(CUR,"scripts","catalog_template.html")).read()
open(os.path.join(CUR,"catalog.html"),'w').write(tpl.replace('__DATA__',json.dumps(out,ensure_ascii=False)).replace('__N__',str(len(out))))
from collections import Counter
tiers=Counter(o['disposition'] for o in out)
print("== APA refresh ==")
print("current set:",os.path.basename(CUR)," docs:",len(out)," tiers:",dict(tiers))
print("rebuilt: library_crosswalk_curated.csv, catalog_data.json, catalog.html")
# ---- diff vs prior crawl by SHA-256 ----
def load_manifest(d):
    p=os.path.join(d,"metadata","manifest.csv")
    if not os.path.exists(p): return None
    rr=list(csv.DictReader(open(p)))
    sha=next((c for c in rr[0] if 'sha' in c.lower()),None)
    url=next((c for c in rr[0] if 'final' in c.lower() and 'url' in c.lower()), next((c for c in rr[0] if 'url' in c.lower()),None))
    return {r[url]:(r.get(sha,''),r) for r in rr if url and r.get(url)}
if PREV:
    a=load_manifest(PREV); b=load_manifest(CUR)
    if a and b:
        new=[u for u in b if u not in a]; rem=[u for u in a if u not in b]
        chg=[u for u in b if u in a and a[u][0]!=b[u][0] and a[u][0] and b[u][0]]
        print(f"\ndiff vs {os.path.basename(PREV)}:  NEW={len(new)}  CHANGED={len(chg)}  REMOVED={len(rem)}")
        for u in new[:20]: print("  + NEW:",u)
        for u in chg[:20]: print("  ~ CHANGED:",u)
        for u in rem[:20]: print("  - REMOVED:",u)
else:
    print("\n(no prior APA_Downloads_* set to diff against)")
