import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const run = spawnSync(process.execPath, ['generate-preview.mjs', '--check'], {
  cwd: root,
  encoding: 'utf8',
});

assert.equal(run.status, 0, run.stdout + run.stderr);

const html = fs.readFileSync(path.join(root, 'sp-interview.preview.html'), 'utf8');
const match = html.match(
  /<!-- GENERATED by generate-preview\.mjs; do not edit directly\. -->\n<script>window\.__SP_PREVIEW__=([\s\S]*?);window\.__SP_PACK__=([\s\S]*?);<\/script>/,
);
assert.ok(match, 'generated preview assignments must be present');

const previewConfig = JSON.parse(match[1]);
const embeddedPack = JSON.parse(match[2]);
const canonicalPack = JSON.parse(
  fs.readFileSync(path.join(root, 'sp-interview.pack.json'), 'utf8'),
);

assert.deepEqual(embeddedPack, canonicalPack);
assert.deepEqual(previewConfig, {
  generated: true,
  providerMode: 'mock',
  endpoint: '',
  autoOpenSettings: false,
});

console.log('PASS — generated preview matches canonical HTML and pack');
